# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            "Jianghao's Garage"
tagline:          ''
description:      'This site contains mostly my thoughts that are neither useful or worth noting. Who knows?'
url:              https://jianghaolu.github.io
baseurl:          /

author:
  name:           'Jianghao Lu'
  url:            https://github.com/jianghaolu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jianghaolu/jianghaolu.github.io
